config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :delete]
  resources :goals
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  author_id  :integer          not null
#  body       :text             not null
#  completed  :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string
#  private    :boolean          not null
#

class Goal < ActiveRecord::Base

  validates :author, :title, :body, presence: true
  validates_inclusion_of :private, in: [true, false]
  validates_inclusion_of :completed, in: [true, false]

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  def status
    completed ? 'Completed' : 'Ongoing'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password

  has_many :goals,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Goal

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil unless user && user.is_password?(password)
    user
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Goal.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login_user!(@user)
      flash[:notice] = "Login successful!"
      redirect_to goals_url
    else
      flash.now[:errors] = ["Incorrect password and/or username"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      flash[:notice] = "User created!"
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1>Goals Index Page</h1>

<ul>
<% @goals.each do |goal| %>
  <% next if goal.private %>
  <li>
    <%= goal.title %> by <%= goal.author.username %> | <i><%= goal.status %></i>
  </li>
<% end %>
</ul>

app/views/layouts/_flash.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <ul>
    <li><%= error %></li>
  </ul>
  <% end %>
<% end %>

<%= flash[:notice] if flash[:notice] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <% if current_user %>
      <%= current_user.username %>
      <%= button_to "Logout", session_url, method: :delete %>
    <%else %>
      <%= link_to "Log in", new_session_url %>
      <%= link_to "Sign up", new_user_url %>
    <%end %>

    <%= render partial: "layouts/flash" %>
  </header>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New user</h1>

<form action="/users" method="POST" >
  <input type="hidden"
    name="authenticity_token"
    value="<%=form_authenticity_token %>">

  <label>username</label>
    <input
      type="text"
      id="username"
      name="user[username]">

  <label>password</label>
    <input
      type="password"
      id="password"
      name="user[password]">

  <input type="submit" value="Create user">
</form>